name: Docs

# Events that trigger this workflow
on:
  push:
    branches:
      - main

# Defines which tool versions should be used in all workflow jobs
env:
  node: '18'
  pnpm: '7'

jobs:
  build-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v3.6.0
      - name: Setup PNPM 💿
        uses: pnpm/action-setup@v2.4.1
        with:
          version: ${{ env.pnpm }}
      - name: Setup Node 💿
        uses: actions/setup-node@v3.9.1
        with:
          node-version: ${{ env.node }}
          cache: 'pnpm'

      - name: Install dependencies 📚
        run: pnpm install
      - name: Build packages 📦
        run: pnpm build
      - name: Build documentation 🛠️
        run: pnpm docs:build

      - name: Deploy documentation 🚀
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages
          folder: docs
